[package]
name = "nostr-zapper"
version = "0.38.0"
edition = "2021"
description = "Zapper abstraction for Nostr apps"
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
readme = "README.md"
rust-version.workspace = true
keywords = ["nostr", "zapper"]

[dependencies]
nostr = { workspace = true, features = ["std"] }
webln = { version = "0.4", optional = true }
