name: Bindings CI

on:
  push:
    branches: [ master ]
    paths:
      - "bindings/nostr-sdk-ffi/**"
  pull_request:
    branches: [ master ]
    paths:
      - "bindings/nostr-sdk-ffi/**"
  workflow_dispatch:

jobs:
  swift:
    name: Swift Package
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install just
        run: cargo install just

      - name: Build Swift Package
        working-directory: bindings/nostr-sdk-ffi
        run: just swift

      - name: Test
        working-directory: bindings/nostr-sdk-ffi/swift
        run: swift test
